/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    technologies: Technology;
    'site-settings': SiteSetting;
    videos: Video;
    projects: Project;
    advisors: Advisor;
    locations: Location;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    locations: {
      employees: 'advisors';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    advisors: AdvisorsSelect<false> | AdvisorsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text is a short written description of this image. Screen readers read it aloud for people who can’t see the image, and browsers show it if the image fails to load. Describe what the image shows and why it matters here — e.g. “Founder presenting the new bakery brand on stage” — not the file name or the word “image”. (Required.)
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: number;
  /**
   * e.g., "React", "Node.js", "AWS"
   */
  name: string;
  /**
   * Official website or documentation (optional)
   */
  url?: string | null;
  /**
   * Categorize the technology for filtering
   */
  category?: ('language' | 'framework' | 'tool' | 'platform' | 'database' | 'service' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * e.g., "Considerate Systems LLC"
   */
  organizationName: string;
  /**
   * What does your organization do?
   */
  organizationDescription?: string | null;
  /**
   * Organization logo (for schema.org and social)
   */
  logo?: (number | null) | Media;
  /**
   * When was the organization founded?
   */
  foundingDate?: string | null;
  /**
   * Physical address or location
   */
  address?: string | null;
  /**
   * Contact email address
   */
  email?: string | null;
  /**
   * Contact phone number
   */
  telephone?: string | null;
  /**
   * First name, e.g., "Mark"
   */
  personGivenName: string;
  /**
   * Last name, e.g., "Musil"
   */
  personFamilyName: string;
  /**
   * e.g., "Founder & Principal Consultant"
   */
  personJobTitle?: string | null;
  /**
   * Professional bio (2-3 sentences)
   */
  personBio?: string | null;
  /**
   * Professional headshot or photo
   */
  personImage?: (number | null) | Media;
  /**
   * Select core expertise/technologies
   */
  personExpertise?: (number | Technology)[] | null;
  /**
   * LinkedIn profile URL (optional)
   */
  linkedinUrl?: string | null;
  /**
   * GitHub profile URL (optional)
   */
  githubUrl?: string | null;
  /**
   * e.g., "$120/hr" - for schema.org Offer
   */
  hourlyRate?: string | null;
  /**
   * Current availability for new projects
   */
  availabilityStatus?: ('available' | 'limited' | 'unavailable') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * High-quality video, transcoded to adaptive HLS. Upload a source file and the pipeline produces a streaming ladder capped at the source quality.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * Internal label, e.g. "Bakery build timelapse"
   */
  title: string;
  /**
   * Alt text is a short description of this video for people using screen readers and as a fallback when the clip can’t play. Describe what the clip shows and its purpose — e.g. “Time-lapse of the bakery storefront being built over three days”. One clear sentence is plenty. (Required.)
   */
  alt: string;
  /**
   * Display width. Portrait (phone) clips look best at Small or Medium.
   */
  displaySize?: ('small' | 'medium' | 'large' | 'full') | null;
  /**
   * Horizontal placement within the column.
   */
  displayAlignment?: ('center' | 'left' | 'right') | null;
  /**
   * Remove the audio track — produces a silent video. Useful for workshop clips where the only sound is computer fans or background noise. Audio is stripped during transcoding, so set this BEFORE uploading the source. To change it on an existing clip, re-upload the source.
   */
  removeAudio?: boolean | null;
  /**
   * Set automatically by the upload + transcode pipeline.
   */
  status?: ('empty' | 'uploading' | 'processing' | 'ready' | 'error') | null;
  /**
   * S3 key of the archived original (ceiling-quality playback).
   */
  sourceKey?: string | null;
  /**
   * MIME type of the original, used by the player to feature-detect direct playback.
   */
  sourceMimeType?: string | null;
  /**
   * S3 key of the HLS master manifest (index.m3u8). Set when transcode completes.
   */
  hlsManifestKey?: string | null;
  /**
   * S3 key of the poster/thumbnail frame.
   */
  posterKey?: string | null;
  /**
   * MediaConvert job id (for debugging).
   */
  mediaConvertJobId?: string | null;
  /**
   * Duration in milliseconds.
   */
  durationMs?: number | null;
  /**
   * Source width (px). The ladder never upscales beyond this.
   */
  width?: number | null;
  /**
   * Source height (px).
   */
  height?: number | null;
  /**
   * Populated if transcoding failed.
   */
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL-safe identifier, e.g. "bakery-rebrand"
   */
  slug: string;
  client?: string | null;
  description?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional video of this project (adaptive HLS, plays on the project page).
   */
  projectVideo?: (number | null) | Video;
  technologies?:
    | {
        tech?: (number | null) | Technology;
        id?: string | null;
      }[]
    | null;
  /**
   * Link to the live site (optional)
   */
  liveUrl?: string | null;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * Configure how search engines and AI interpret this project. Fields auto-map from the content above.
   */
  structuredData: {
    /**
     * Choose the schema type that best describes this project.
     */
    schemaType: 'CreativeWork' | 'WebApplication' | 'SoftwareSourceCode' | 'Service';
    /**
     * Quantifiable results or impact (e.g., "Reduced latency by 40%", "Shipped in 2 months")
     */
    outcomes?: string | null;
    /**
     * SEO keywords that describe this project
     */
    keywordsFocused?:
      | {
          /**
           * e.g., "React development", "Cloud migration"
           */
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisors".
 */
export interface Advisor {
  id: number;
  firstName: string;
  lastName: string;
  headshot?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The office this advisor works from
   */
  location?: (number | null) | Location;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * Office name, e.g. "Raleigh Headquarters"
   */
  name: string;
  /**
   * Full street address
   */
  address?: string | null;
  coordinates?: {
    /**
     * e.g. 35.7796
     */
    latitude?: number | null;
    /**
     * e.g. -78.6382
     */
    longitude?: number | null;
  };
  officeImage?: (number | null) | Media;
  employees?: {
    docs?: (number | Advisor)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'technologies';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'advisors';
        value: number | Advisor;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organizationName?: T;
  organizationDescription?: T;
  logo?: T;
  foundingDate?: T;
  address?: T;
  email?: T;
  telephone?: T;
  personGivenName?: T;
  personFamilyName?: T;
  personJobTitle?: T;
  personBio?: T;
  personImage?: T;
  personExpertise?: T;
  linkedinUrl?: T;
  githubUrl?: T;
  hourlyRate?: T;
  availabilityStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  displaySize?: T;
  displayAlignment?: T;
  removeAudio?: T;
  status?: T;
  sourceKey?: T;
  sourceMimeType?: T;
  hlsManifestKey?: T;
  posterKey?: T;
  mediaConvertJobId?: T;
  durationMs?: T;
  width?: T;
  height?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  description?: T;
  body?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  projectVideo?: T;
  technologies?:
    | T
    | {
        tech?: T;
        id?: T;
      };
  liveUrl?: T;
  featured?: T;
  publishedAt?: T;
  structuredData?:
    | T
    | {
        schemaType?: T;
        outcomes?: T;
        keywordsFocused?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisors_select".
 */
export interface AdvisorsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  headshot?: T;
  bio?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  officeImage?: T;
  employees?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InlineVideoBlock".
 */
export interface InlineVideoBlock {
  /**
   * Pick a clip, or create + upload a new one inline.
   */
  video: number | Video;
  /**
   * Optional caption shown beneath the clip.
   */
  caption?: string | null;
  /**
   * Display width for THIS placement. Leave blank to use the clip default. Portrait clips look best at Small or Medium.
   */
  displaySize?: ('small' | 'medium' | 'large' | 'full') | null;
  /**
   * Horizontal placement within the column. Leave blank to use the clip default.
   */
  displayAlignment?: ('center' | 'left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGridBlock".
 */
export interface ImageGridBlock {
  /**
   * Add images and drag to reorder. They flow into the grid left-to-right.
   */
  images: {
    image: number | Media;
    /**
     * Optional — overrides the alt text just for this cell. Leave blank to use the alt text saved on the image itself (which is required).
     */
    alt?: string | null;
    /**
     * Optional caption shown beneath this image.
     */
    caption?: string | null;
    id?: string | null;
  }[];
  /**
   * How many columns the grid uses. "Auto-fit" packs as many as the width allows.
   */
  columns?: ('auto' | '2' | '3' | '4') | null;
  /**
   * Spacing between images.
   */
  gap?: ('none' | 'small' | 'medium' | 'large') | null;
  /**
   * Crop every cell to a uniform shape, or keep each image’s natural proportions.
   */
  aspectRatio?: ('auto' | 'square' | 'landscape' | 'wide' | 'portrait') | null;
  /**
   * Round the corners of every image in the grid.
   */
  borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'full') | null;
  /**
   * Drop shadow depth behind every image in the grid.
   */
  shadow?: ('none' | 'small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}